---
title: "Estadística Espacial - Práctica Integradora"
author: "Achenbach, Paula; Salvo, Martin; Pelli, Nahuel"
date: "3/19/2022"
output:
    html_document:
        code_folding: show
        df_print: paged
        toc: true
        number_sections: true
        toc_float:
          collapsed: false
          smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

***Inicialización de librerias***
```{r require.libs, include=FALSE}
if(!require(pacman)) install.packages("pacman")
pacman::p_load(
    'gstat',
    'geoR',
    'ggplot2',
    'spdep',
    'sp',
    'dplyr',
    'automap',
    'rgdal',
    'udunit2'
)

load(file = "./data/spain_geodata_temperature_1989_spring.RData")

```

Para este trabajo tenemos un grupo grande de librerias a utilizar. Vamos a separar por su
funcionalidad.

```{r init, warning=FALSE, message=FALSE}
## librerias básicas
library(dplyr)
library(ggplot2)
library(raster)
library(readr)

## Librerias de geo estadística
library(geoR)
library(gstat)
library(rgdal)
library(sp)
library(spdep)

## Librerias auxiliares
library(automap)
library(FNN)
library(lattice)
library(udunits2)

```


```{r, child='content/seccion_1.Rmd'}
```
\newpage
```{r, child='content/seccion_2.Rmd'}
```
\newpage
```{r, child='content/seccion_3_variogramas.Rmd'}
```
\newpage
```{r, child='content/seccion_4_krigging.Rmd'}
```

\newpage
```{r, child='content/seccion_5_preguntas_teoricas.Rmd'}
```
\newpage

